"""
LOBSTER data loader.
Reads orderbook + message CSV files directly from zip archives in data/raw/.
"""

import zipfile
from pathlib import Path
import numpy as np
import pandas as pd

DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "raw"

# Orderbook column layout for N levels: [AskP1,AskS1,BidP1,BidS1, AskP2,AskS2,BidP2,BidS2, ...]
# Message columns: [Time, Type, OrderID, Size, Price, Direction]

def _orderbook_columns(n_levels: int) -> list[str]:
    cols = []
    for i in range(1, n_levels + 1):
        cols += [f"ask_price_{i}", f"ask_size_{i}", f"bid_price_{i}", f"bid_size_{i}"]
    return cols


def load_lobster(symbol: str, date: str, n_levels: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Returns (orderbook_df, message_df) for the given symbol/date/levels.

    Prices in the returned DataFrames are in dollars (converted from price×10000).
    """
    pattern = f"LOBSTER_SampleFile_{symbol}_{date}_{n_levels}.zip"
    zip_path = DATA_DIR / pattern
    if not zip_path.exists():
        raise FileNotFoundError(f"No zip found: {zip_path}")

    with zipfile.ZipFile(zip_path) as zf:
        # Find the orderbook and message files inside
        names = zf.namelist()
        ob_file = next(n for n in names if "orderbook" in n and n.endswith(".csv"))
        msg_file = next(n for n in names if "message" in n and n.endswith(".csv"))

        ob_cols = _orderbook_columns(n_levels)
        with zf.open(ob_file) as f:
            ob = pd.read_csv(f, header=None, names=ob_cols, dtype=np.float64)

        msg_cols = ["time", "type", "order_id", "size", "price", "direction"]
        with zf.open(msg_file) as f:
            msg = pd.read_csv(f, header=None, names=msg_cols, dtype=np.float64)

    # Convert prices from int×10000 to dollars
    for col in ob.columns:
        if "price" in col:
            # Mask dummy values (±9999999999) before converting
            dummy_ask = ob[col] >= 9_000_000_000
            dummy_bid = ob[col] <= -9_000_000_000
            ob[col] = ob[col] / 10_000.0
            ob.loc[dummy_ask, col] = np.nan
            ob.loc[dummy_bid, col] = np.nan

    msg["price"] = msg["price"] / 10_000.0

    # Attach timestamp from message file
    ob["time"] = msg["time"].values

    return ob, msg


def load_synthetic(csv_dir: Path | str, n_levels: int = 5) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Load synthetic data generated by eXSimulator's lob_export tool.
    Expects files: SYNTHETIC_<date>_..._orderbook_<n>.csv and _message_<n>.csv
    in csv_dir (plain CSV, not zipped).
    """
    csv_dir = Path(csv_dir)
    ob_files  = sorted(csv_dir.glob(f"SYNTHETIC_*_orderbook_{n_levels}.csv"))
    msg_files = sorted(csv_dir.glob(f"SYNTHETIC_*_message_{n_levels}.csv"))
    if not ob_files:
        raise FileNotFoundError(f"No synthetic orderbook CSV in {csv_dir}")

    ob_cols  = _orderbook_columns(n_levels)
    msg_cols = ["time", "type", "order_id", "size", "price", "direction"]

    ob  = pd.read_csv(ob_files[0],  header=None, names=ob_cols,  dtype=np.float64)
    msg = pd.read_csv(msg_files[0], header=None, names=msg_cols, dtype=np.float64)

    # Prices already in PRICE_SCALE units from eXSimulator — convert same way
    for col in ob.columns:
        if "price" in col:
            dummy_ask = ob[col] >= 9_000_000_000
            dummy_bid = ob[col] <= -9_000_000_000
            ob[col] = ob[col] / 10_000.0
            ob.loc[dummy_ask, col] = np.nan
            ob.loc[dummy_bid, col] = np.nan

    ob["time"] = msg["time"].values
    return ob, msg


def load_all(n_levels: int = 5) -> dict[str, tuple[pd.DataFrame, pd.DataFrame]]:
    """Load all available symbols for the given level depth."""
    results = {}
    for zip_path in sorted(DATA_DIR.glob(f"*_{n_levels}.zip")):
        parts = zip_path.stem.split("_")
        # LOBSTER_SampleFile_AAPL_2012-06-21_5
        symbol = parts[2]
        date = parts[3]
        try:
            results[symbol] = load_lobster(symbol, date, n_levels)
        except Exception as e:
            print(f"[warn] skipping {symbol}: {e}")
    return results


if __name__ == "__main__":
    ob, msg = load_lobster("AAPL", "2012-06-21", 5)
    print(f"Orderbook: {ob.shape}  Messages: {msg.shape}")
    print(ob.head(3))
    print(msg.head(3))
